GH Actions CI: setup -> cancel-runs, etc.

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -18,7 +18,7 @@ permissions:
   id-token: write
 
 jobs:
-  setup:
+  cancel-runs:
     runs-on: ubuntu-latest
 
     steps:
@@ -43,7 +43,6 @@ jobs:
           profile: minimal
           toolchain: nightly
           override: true
-          components: rustfmt, clippy
 
       - name: Run tests
         uses: actions-rs/cargo@v1
@@ -64,7 +63,7 @@ jobs:
           profile: minimal
           toolchain: nightly
           override: true
-          components: rustfmt, clippy
+          components: rustfmt
 
       - name: Configure git credentials
         run: |
@@ -78,8 +77,9 @@ jobs:
           args: --all
 
       - name: Commit formatting changes
+        # Commit changes, or, if that fails, do nothing.
         run: |
-          git commit -am "Formatted code with rustfmt ${{ github.run_number }}" || echo "Nothing to be formatted!"
+          git commit -am "Formatted code with rustfmt ${{ github.run_number }}" || :
 
       - name: Push changes
         run: git push
@@ -97,7 +97,7 @@ jobs:
           profile: minimal
           toolchain: nightly
           override: true
-          components: rustfmt, clippy
+          components: clippy
 
       - name: Configure git credentials
         run: |
@@ -111,8 +111,9 @@ jobs:
           args: --workspace --fix --color always
 
       - name: Commit fixes
+        # Commit changes, or, if that fails, do nothing.
         run: |
-          git commit -am "Applied recommended fixes ${{ github.run_number }}" || echo "Nothing to be fixed!"
+          git commit -am "Applied recommended fixes ${{ github.run_number }}" || :
 
       - name: Push changes
         run: git push
@@ -168,7 +169,6 @@ jobs:
           profile: minimal
           toolchain: nightly
           override: true
-          components: rustfmt, clippy
 
       # Setup GitHub Pages to easily deploy to it.
       - name: Setup GitHub Pages
