GH Actions CI: auto-format needs: clippy-fixes

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -50,40 +50,6 @@ jobs:
           command: test
           args: --workspace --color always
 
-  auto-format:
-    runs-on: ubuntu-latest
-
-    steps:
-      - name: Checkout XRB
-        uses: actions/checkout@v3
-
-      - name: Install latest nightly
-        uses: actions-rs/toolchain@v1
-        with:
-          profile: minimal
-          toolchain: nightly
-          override: true
-          components: rustfmt
-
-      - name: Configure git credentials
-        run: |
-          git config user.name github-actions
-          git config user.email github-actions@github.com
-
-      - name: Format code with rustfmt
-        uses: actions-rs/cargo@v1
-        with:
-          command: fmt
-          args: --all
-
-      - name: Commit formatting changes
-        # Commit changes, or, if that fails, do nothing.
-        run: |
-          git commit -am "Formatted code with rustfmt ${{ github.run_number }}" || :
-
-      - name: Push changes
-        run: git pull && git push
-
   clippy-fixes:
     runs-on: ubuntu-latest
 
@@ -140,6 +106,41 @@ jobs:
         with:
           command: clippy
           args: --workspace --color always
+
+  auto-format:
+    runs-on: ubuntu-latest
+    needs: clippy-fixes
+
+    steps:
+      - name: Checkout XRB
+        uses: actions/checkout@v3
+
+      - name: Install latest nightly
+        uses: actions-rs/toolchain@v1
+        with:
+          profile: minimal
+          toolchain: nightly
+          override: true
+          components: rustfmt
+
+      - name: Configure git credentials
+        run: |
+          git config user.name github-actions
+          git config user.email github-actions@github.com
+
+      - name: Format code with rustfmt
+        uses: actions-rs/cargo@v1
+        with:
+          command: fmt
+          args: --all
+
+      - name: Commit formatting changes
+        # Commit changes, or, if that fails, do nothing.
+        run: |
+          git commit -am "Formatted code with rustfmt ${{ github.run_number }}" || :
+
+      - name: Push changes
+        run: git pull && git push
 
   # Generate the docs with rustdoc.
   build-docs:
